package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/so1icitx/StockWise/internal/application"
	"github.com/so1icitx/StockWise/internal/domain"
	"github.com/so1icitx/StockWise/internal/transport/graphql/generated"
	"github.com/so1icitx/StockWise/internal/transport/graphql/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user, err := r.services.Users.Create(ctx, application.CreateUserInput{
		Name:  input.Name,
		Email: input.Email,
		Role:  domain.UserRole(input.Role),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLUser(*user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	userID, err := parseID(id, "user id")
	if err != nil {
		return nil, err
	}

	user, err := r.services.Users.Update(ctx, userID, application.UpdateUserInput{
		Name:     input.Name,
		Email:    input.Email,
		Role:     domain.UserRole(input.Role),
		IsActive: input.IsActive,
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLUser(*user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID, err := parseID(id, "user id")
	if err != nil {
		return false, err
	}

	return true, r.services.Users.Delete(ctx, userID)
}

// CreateWarehouse is the resolver for the createWarehouse field.
func (r *mutationResolver) CreateWarehouse(ctx context.Context, input model.WarehouseInput) (*model.Warehouse, error) {
	warehouse, err := r.services.Warehouses.Create(ctx, application.CreateWarehouseInput{
		Name:     input.Name,
		Code:     input.Code,
		Location: optionalString(input.Location),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLWarehouse(*warehouse), nil
}

// UpdateWarehouse is the resolver for the updateWarehouse field.
func (r *mutationResolver) UpdateWarehouse(ctx context.Context, id string, input model.WarehouseInput) (*model.Warehouse, error) {
	warehouseID, err := parseID(id, "warehouse id")
	if err != nil {
		return nil, err
	}
	current, err := r.services.Warehouses.GetByID(ctx, warehouseID)
	if err != nil {
		return nil, err
	}

	warehouse, err := r.services.Warehouses.Update(ctx, warehouseID, application.UpdateWarehouseInput{
		Name:     input.Name,
		Code:     input.Code,
		Location: optionalStringWithFallback(input.Location, current.Location),
		IsActive: optionalBool(input.IsActive, current.IsActive),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLWarehouse(*warehouse), nil
}

// DeleteWarehouse is the resolver for the deleteWarehouse field.
func (r *mutationResolver) DeleteWarehouse(ctx context.Context, id string) (bool, error) {
	warehouseID, err := parseID(id, "warehouse id")
	if err != nil {
		return false, err
	}

	return true, r.services.Warehouses.Delete(ctx, warehouseID)
}

// ActivateWarehouse is the resolver for the activateWarehouse field.
func (r *mutationResolver) ActivateWarehouse(ctx context.Context, id string) (bool, error) {
	warehouseID, err := parseID(id, "warehouse id")
	if err != nil {
		return false, err
	}

	return true, r.services.Warehouses.Activate(ctx, warehouseID)
}

// DeactivateWarehouse is the resolver for the deactivateWarehouse field.
func (r *mutationResolver) DeactivateWarehouse(ctx context.Context, id string) (bool, error) {
	warehouseID, err := parseID(id, "warehouse id")
	if err != nil {
		return false, err
	}

	return true, r.services.Warehouses.Deactivate(ctx, warehouseID)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CategoryInput) (*model.Category, error) {
	category, err := r.services.Categories.Create(ctx, application.CreateCategoryInput{
		Name:        input.Name,
		Description: optionalString(input.Description),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLCategory(*category), nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.CategoryInput) (*model.Category, error) {
	categoryID, err := parseID(id, "category id")
	if err != nil {
		return nil, err
	}
	current, err := r.services.Categories.GetByID(ctx, categoryID)
	if err != nil {
		return nil, err
	}

	category, err := r.services.Categories.Update(ctx, categoryID, application.UpdateCategoryInput{
		Name:        input.Name,
		Description: optionalStringWithFallback(input.Description, current.Description),
		IsActive:    optionalBool(input.IsActive, current.IsActive),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLCategory(*category), nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	categoryID, err := parseID(id, "category id")
	if err != nil {
		return false, err
	}

	return true, r.services.Categories.Delete(ctx, categoryID)
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.ProductInput) (*model.Product, error) {
	categoryID, err := parseID(input.CategoryID, "category id")
	if err != nil {
		return nil, err
	}

	product, err := r.services.Products.Create(ctx, application.CreateProductInput{
		Name:              input.Name,
		SKU:               input.Sku,
		CategoryID:        categoryID,
		UnitOfMeasure:     input.UnitOfMeasure,
		MinStockThreshold: int64(input.MinStockThreshold),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLProduct(*product), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.ProductInput) (*model.Product, error) {
	productID, err := parseID(id, "product id")
	if err != nil {
		return nil, err
	}
	categoryID, err := parseID(input.CategoryID, "category id")
	if err != nil {
		return nil, err
	}
	current, err := r.services.Products.GetByID(ctx, productID)
	if err != nil {
		return nil, err
	}

	product, err := r.services.Products.Update(ctx, productID, application.UpdateProductInput{
		Name:              input.Name,
		SKU:               input.Sku,
		CategoryID:        categoryID,
		UnitOfMeasure:     input.UnitOfMeasure,
		MinStockThreshold: int64(input.MinStockThreshold),
		IsActive:          optionalBool(input.IsActive, current.IsActive),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLProduct(*product), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	productID, err := parseID(id, "product id")
	if err != nil {
		return false, err
	}

	return true, r.services.Products.Delete(ctx, productID)
}

// ActivateProduct is the resolver for the activateProduct field.
func (r *mutationResolver) ActivateProduct(ctx context.Context, id string) (bool, error) {
	productID, err := parseID(id, "product id")
	if err != nil {
		return false, err
	}

	return true, r.services.Products.Activate(ctx, productID)
}

// DeactivateProduct is the resolver for the deactivateProduct field.
func (r *mutationResolver) DeactivateProduct(ctx context.Context, id string) (bool, error) {
	productID, err := parseID(id, "product id")
	if err != nil {
		return false, err
	}

	return true, r.services.Products.Deactivate(ctx, productID)
}

// CreateSupply is the resolver for the createSupply field.
func (r *mutationResolver) CreateSupply(ctx context.Context, input model.CreateSupplyInput) (*model.Supply, error) {
	warehouseID, err := parseID(input.WarehouseID, "warehouse id")
	if err != nil {
		return nil, err
	}
	userID, err := parseID(input.CreatedByUserID, "created by user id")
	if err != nil {
		return nil, err
	}

	supply, err := r.services.Supplies.Create(ctx, application.CreateSupplyInput{
		WarehouseID:     warehouseID,
		CreatedByUserID: userID,
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLSupply(*supply), nil
}

// AddSupplyItem is the resolver for the addSupplyItem field.
func (r *mutationResolver) AddSupplyItem(ctx context.Context, supplyID string, input model.SupplyItemInput) (*model.SupplyItem, error) {
	id, productID, err := parseOperationAndProductIDs(supplyID, input.ProductID, "supply id")
	if err != nil {
		return nil, err
	}

	item, err := r.services.Supplies.AddItem(ctx, id, application.SupplyItemInput{
		ProductID:      productID,
		Quantity:       int64(input.Quantity),
		UnitPriceCents: int64(input.UnitPriceCents),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLSupplyItem(*item), nil
}

// UpdateSupplyItem is the resolver for the updateSupplyItem field.
func (r *mutationResolver) UpdateSupplyItem(ctx context.Context, supplyID string, itemID string, input model.SupplyItemInput) (*model.SupplyItem, error) {
	id, item, productID, err := parseOperationItemAndProductIDs(supplyID, itemID, input.ProductID, "supply id", "supply item id")
	if err != nil {
		return nil, err
	}

	updated, err := r.services.Supplies.UpdateItem(ctx, id, item, application.SupplyItemInput{
		ProductID:      productID,
		Quantity:       int64(input.Quantity),
		UnitPriceCents: int64(input.UnitPriceCents),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLSupplyItem(*updated), nil
}

// DeleteSupplyItem is the resolver for the deleteSupplyItem field.
func (r *mutationResolver) DeleteSupplyItem(ctx context.Context, supplyID string, itemID string) (bool, error) {
	id, item, err := parseOperationItemIDs(supplyID, itemID, "supply id", "supply item id")
	if err != nil {
		return false, err
	}

	return true, r.services.Supplies.DeleteItem(ctx, id, item)
}

// ConfirmSupply is the resolver for the confirmSupply field.
func (r *mutationResolver) ConfirmSupply(ctx context.Context, id string, userID string) (*model.Supply, error) {
	supplyID, user, err := parseOperationActorIDs(id, userID, "supply id")
	if err != nil {
		return nil, err
	}

	supply, err := r.services.Supplies.Confirm(ctx, supplyID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLSupply(*supply), nil
}

// CancelSupply is the resolver for the cancelSupply field.
func (r *mutationResolver) CancelSupply(ctx context.Context, id string, userID string) (*model.Supply, error) {
	supplyID, user, err := parseOperationActorIDs(id, userID, "supply id")
	if err != nil {
		return nil, err
	}

	supply, err := r.services.Supplies.Cancel(ctx, supplyID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLSupply(*supply), nil
}

// DeleteSupply is the resolver for the deleteSupply field.
func (r *mutationResolver) DeleteSupply(ctx context.Context, id string) (bool, error) {
	supplyID, err := parseID(id, "supply id")
	if err != nil {
		return false, err
	}

	return true, r.services.Supplies.Delete(ctx, supplyID)
}

// CreateOutboundRequest is the resolver for the createOutboundRequest field.
func (r *mutationResolver) CreateOutboundRequest(ctx context.Context, input model.CreateOutboundRequestInput) (*model.OutboundRequest, error) {
	warehouseID, err := parseID(input.WarehouseID, "warehouse id")
	if err != nil {
		return nil, err
	}
	userID, err := parseID(input.CreatedByUserID, "created by user id")
	if err != nil {
		return nil, err
	}

	request, err := r.services.OutboundRequests.Create(ctx, application.CreateOutboundRequestInput{
		WarehouseID:     warehouseID,
		CreatedByUserID: userID,
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequest(*request), nil
}

// AddOutboundRequestItem is the resolver for the addOutboundRequestItem field.
func (r *mutationResolver) AddOutboundRequestItem(ctx context.Context, outboundRequestID string, input model.OutboundRequestItemInput) (*model.OutboundRequestItem, error) {
	id, productID, err := parseOperationAndProductIDs(outboundRequestID, input.ProductID, "outbound request id")
	if err != nil {
		return nil, err
	}

	item, err := r.services.OutboundRequests.AddItem(ctx, id, application.OutboundRequestItemInput{
		ProductID: productID,
		Quantity:  int64(input.Quantity),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequestItem(*item), nil
}

// UpdateOutboundRequestItem is the resolver for the updateOutboundRequestItem field.
func (r *mutationResolver) UpdateOutboundRequestItem(ctx context.Context, outboundRequestID string, itemID string, input model.OutboundRequestItemInput) (*model.OutboundRequestItem, error) {
	id, item, productID, err := parseOperationItemAndProductIDs(outboundRequestID, itemID, input.ProductID, "outbound request id", "outbound request item id")
	if err != nil {
		return nil, err
	}

	updated, err := r.services.OutboundRequests.UpdateItem(ctx, id, item, application.OutboundRequestItemInput{
		ProductID: productID,
		Quantity:  int64(input.Quantity),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequestItem(*updated), nil
}

// DeleteOutboundRequestItem is the resolver for the deleteOutboundRequestItem field.
func (r *mutationResolver) DeleteOutboundRequestItem(ctx context.Context, outboundRequestID string, itemID string) (bool, error) {
	id, item, err := parseOperationItemIDs(outboundRequestID, itemID, "outbound request id", "outbound request item id")
	if err != nil {
		return false, err
	}

	return true, r.services.OutboundRequests.DeleteItem(ctx, id, item)
}

// ApproveOutboundRequest is the resolver for the approveOutboundRequest field.
func (r *mutationResolver) ApproveOutboundRequest(ctx context.Context, id string, userID string) (*model.OutboundRequest, error) {
	requestID, user, err := parseOperationActorIDs(id, userID, "outbound request id")
	if err != nil {
		return nil, err
	}

	request, err := r.services.OutboundRequests.Approve(ctx, requestID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequest(*request), nil
}

// RejectOutboundRequest is the resolver for the rejectOutboundRequest field.
func (r *mutationResolver) RejectOutboundRequest(ctx context.Context, id string, userID string) (*model.OutboundRequest, error) {
	requestID, user, err := parseOperationActorIDs(id, userID, "outbound request id")
	if err != nil {
		return nil, err
	}

	request, err := r.services.OutboundRequests.Reject(ctx, requestID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequest(*request), nil
}

// CancelOutboundRequest is the resolver for the cancelOutboundRequest field.
func (r *mutationResolver) CancelOutboundRequest(ctx context.Context, id string, userID string) (*model.OutboundRequest, error) {
	requestID, user, err := parseOperationActorIDs(id, userID, "outbound request id")
	if err != nil {
		return nil, err
	}

	request, err := r.services.OutboundRequests.Cancel(ctx, requestID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequest(*request), nil
}

// ExecuteOutboundRequest is the resolver for the executeOutboundRequest field.
func (r *mutationResolver) ExecuteOutboundRequest(ctx context.Context, id string, userID string) (*model.OutboundRequest, error) {
	requestID, user, err := parseOperationActorIDs(id, userID, "outbound request id")
	if err != nil {
		return nil, err
	}

	request, err := r.services.OutboundRequests.Execute(ctx, requestID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequest(*request), nil
}

// DeleteOutboundRequest is the resolver for the deleteOutboundRequest field.
func (r *mutationResolver) DeleteOutboundRequest(ctx context.Context, id string) (bool, error) {
	requestID, err := parseID(id, "outbound request id")
	if err != nil {
		return false, err
	}

	return true, r.services.OutboundRequests.Delete(ctx, requestID)
}

// CreateTransfer is the resolver for the createTransfer field.
func (r *mutationResolver) CreateTransfer(ctx context.Context, input model.CreateTransferInput) (*model.Transfer, error) {
	sourceWarehouseID, err := parseID(input.SourceWarehouseID, "source warehouse id")
	if err != nil {
		return nil, err
	}
	targetWarehouseID, err := parseID(input.TargetWarehouseID, "target warehouse id")
	if err != nil {
		return nil, err
	}
	userID, err := parseID(input.CreatedByUserID, "created by user id")
	if err != nil {
		return nil, err
	}

	transfer, err := r.services.Transfers.Create(ctx, application.CreateTransferInput{
		SourceWarehouseID: sourceWarehouseID,
		TargetWarehouseID: targetWarehouseID,
		CreatedByUserID:   userID,
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLTransfer(*transfer), nil
}

// AddTransferItem is the resolver for the addTransferItem field.
func (r *mutationResolver) AddTransferItem(ctx context.Context, transferID string, input model.TransferItemInput) (*model.TransferItem, error) {
	id, productID, err := parseOperationAndProductIDs(transferID, input.ProductID, "transfer id")
	if err != nil {
		return nil, err
	}

	item, err := r.services.Transfers.AddItem(ctx, id, application.TransferItemInput{
		ProductID: productID,
		Quantity:  int64(input.Quantity),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLTransferItem(*item), nil
}

// UpdateTransferItem is the resolver for the updateTransferItem field.
func (r *mutationResolver) UpdateTransferItem(ctx context.Context, transferID string, itemID string, input model.TransferItemInput) (*model.TransferItem, error) {
	id, item, productID, err := parseOperationItemAndProductIDs(transferID, itemID, input.ProductID, "transfer id", "transfer item id")
	if err != nil {
		return nil, err
	}

	updated, err := r.services.Transfers.UpdateItem(ctx, id, item, application.TransferItemInput{
		ProductID: productID,
		Quantity:  int64(input.Quantity),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLTransferItem(*updated), nil
}

// DeleteTransferItem is the resolver for the deleteTransferItem field.
func (r *mutationResolver) DeleteTransferItem(ctx context.Context, transferID string, itemID string) (bool, error) {
	id, item, err := parseOperationItemIDs(transferID, itemID, "transfer id", "transfer item id")
	if err != nil {
		return false, err
	}

	return true, r.services.Transfers.DeleteItem(ctx, id, item)
}

// ConfirmTransfer is the resolver for the confirmTransfer field.
func (r *mutationResolver) ConfirmTransfer(ctx context.Context, id string, userID string) (*model.Transfer, error) {
	transferID, user, err := parseOperationActorIDs(id, userID, "transfer id")
	if err != nil {
		return nil, err
	}

	transfer, err := r.services.Transfers.Confirm(ctx, transferID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLTransfer(*transfer), nil
}

// CancelTransfer is the resolver for the cancelTransfer field.
func (r *mutationResolver) CancelTransfer(ctx context.Context, id string, userID string) (*model.Transfer, error) {
	transferID, user, err := parseOperationActorIDs(id, userID, "transfer id")
	if err != nil {
		return nil, err
	}

	transfer, err := r.services.Transfers.Cancel(ctx, transferID, user)
	if err != nil {
		return nil, err
	}

	return toGraphQLTransfer(*transfer), nil
}

// DeleteTransfer is the resolver for the deleteTransfer field.
func (r *mutationResolver) DeleteTransfer(ctx context.Context, id string) (bool, error) {
	transferID, err := parseID(id, "transfer id")
	if err != nil {
		return false, err
	}

	return true, r.services.Transfers.Delete(ctx, transferID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, role *string, isActive *bool, search *string, limit *int, offset *int) ([]*model.User, error) {
	var roleFilter *domain.UserRole
	if role != nil {
		value := domain.UserRole(*role)
		roleFilter = &value
	}

	users, err := r.services.Users.List(ctx, application.UserFilter{
		Role:        roleFilter,
		IsActive:    isActive,
		Search:      optionalString(search),
		ListOptions: listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLUsers(users), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := parseID(id, "user id")
	if err != nil {
		return nil, err
	}

	user, err := r.services.Users.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}

	return toGraphQLUser(*user), nil
}

// Warehouses is the resolver for the warehouses field.
func (r *queryResolver) Warehouses(ctx context.Context, isActive *bool, code *string, search *string, limit *int, offset *int) ([]*model.Warehouse, error) {
	warehouses, err := r.services.Warehouses.List(ctx, application.WarehouseFilter{
		IsActive:    isActive,
		Code:        optionalString(code),
		Search:      optionalString(search),
		ListOptions: listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLWarehouses(warehouses), nil
}

// Warehouse is the resolver for the warehouse field.
func (r *queryResolver) Warehouse(ctx context.Context, id string) (*model.Warehouse, error) {
	warehouseID, err := parseID(id, "warehouse id")
	if err != nil {
		return nil, err
	}

	warehouse, err := r.services.Warehouses.GetByID(ctx, warehouseID)
	if err != nil {
		return nil, err
	}

	return toGraphQLWarehouse(*warehouse), nil
}

// WarehouseStock is the resolver for the warehouseStock field.
func (r *queryResolver) WarehouseStock(ctx context.Context, warehouseID string) ([]*model.StockItem, error) {
	id, err := parseID(warehouseID, "warehouse id")
	if err != nil {
		return nil, err
	}

	stockItems, err := r.services.Stock.GetByWarehouse(ctx, id)
	if err != nil {
		return nil, err
	}

	return toGraphQLStockItems(stockItems), nil
}

// WarehouseMovements is the resolver for the warehouseMovements field.
func (r *queryResolver) WarehouseMovements(ctx context.Context, warehouseID string, limit *int, offset *int) ([]*model.Movement, error) {
	id, err := parseID(warehouseID, "warehouse id")
	if err != nil {
		return nil, err
	}

	movements, err := r.services.Movements.ListByWarehouse(ctx, id, listOptions(limit, offset))
	if err != nil {
		return nil, err
	}

	return toGraphQLMovements(movements), nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, isActive *bool, search *string, limit *int, offset *int) ([]*model.Category, error) {
	categories, err := r.services.Categories.List(ctx, application.CategoryFilter{
		IsActive:    isActive,
		Search:      optionalString(search),
		ListOptions: listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLCategories(categories), nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	categoryID, err := parseID(id, "category id")
	if err != nil {
		return nil, err
	}

	category, err := r.services.Categories.GetByID(ctx, categoryID)
	if err != nil {
		return nil, err
	}

	return toGraphQLCategory(*category), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, categoryID *string, isActive *bool, sku *string, name *string, search *string, limit *int, offset *int) ([]*model.Product, error) {
	parsedCategoryID, err := parseOptionalID(categoryID, "category id")
	if err != nil {
		return nil, err
	}

	products, err := r.services.Products.List(ctx, application.ProductFilter{
		CategoryID:  parsedCategoryID,
		IsActive:    isActive,
		SKU:         optionalString(sku),
		Name:        optionalString(name),
		Search:      optionalString(search),
		ListOptions: listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLProducts(products), nil
}

// ProductsByCategory is the resolver for the productsByCategory field.
func (r *queryResolver) ProductsByCategory(ctx context.Context, categoryID string, limit *int, offset *int) ([]*model.Product, error) {
	id, err := parseID(categoryID, "category id")
	if err != nil {
		return nil, err
	}

	products, err := r.services.Products.List(ctx, application.ProductFilter{
		CategoryID:  &id,
		ListOptions: listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLProducts(products), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	productID, err := parseID(id, "product id")
	if err != nil {
		return nil, err
	}

	product, err := r.services.Products.GetByID(ctx, productID)
	if err != nil {
		return nil, err
	}

	return toGraphQLProduct(*product), nil
}

// ProductStock is the resolver for the productStock field.
func (r *queryResolver) ProductStock(ctx context.Context, productID string) ([]*model.StockItem, error) {
	id, err := parseID(productID, "product id")
	if err != nil {
		return nil, err
	}

	stockItems, err := r.services.Stock.GetByProductAcrossWarehouses(ctx, id)
	if err != nil {
		return nil, err
	}

	return toGraphQLStockItems(stockItems), nil
}

// ProductTotalStock is the resolver for the productTotalStock field.
func (r *queryResolver) ProductTotalStock(ctx context.Context, productID string) (*model.TotalStock, error) {
	id, err := parseID(productID, "product id")
	if err != nil {
		return nil, err
	}

	quantity, err := r.services.Stock.GetTotalQuantityForProduct(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.TotalStock{ProductID: idString(id), Quantity: int(quantity)}, nil
}

// LowStockProducts is the resolver for the lowStockProducts field.
func (r *queryResolver) LowStockProducts(ctx context.Context) ([]*model.StockStatus, error) {
	statuses, err := r.services.Stock.GetLowStock(ctx)
	if err != nil {
		return nil, err
	}

	return toGraphQLStockStatuses(statuses), nil
}

// ProductMovements is the resolver for the productMovements field.
func (r *queryResolver) ProductMovements(ctx context.Context, productID string, limit *int, offset *int) ([]*model.Movement, error) {
	id, err := parseID(productID, "product id")
	if err != nil {
		return nil, err
	}

	movements, err := r.services.Movements.ListByProduct(ctx, id, listOptions(limit, offset))
	if err != nil {
		return nil, err
	}

	return toGraphQLMovements(movements), nil
}

// Supplies is the resolver for the supplies field.
func (r *queryResolver) Supplies(ctx context.Context, warehouseID *string, status *string, limit *int, offset *int) ([]*model.Supply, error) {
	parsedWarehouseID, err := parseOptionalID(warehouseID, "warehouse id")
	if err != nil {
		return nil, err
	}
	var statusFilter *domain.SupplyStatus
	if status != nil {
		value := domain.SupplyStatus(*status)
		statusFilter = &value
	}

	supplies, err := r.services.Supplies.List(ctx, application.SupplyFilter{
		WarehouseID: parsedWarehouseID,
		Status:      statusFilter,
		ListOptions: listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLSupplies(supplies), nil
}

// Supply is the resolver for the supply field.
func (r *queryResolver) Supply(ctx context.Context, id string) (*model.Supply, error) {
	supplyID, err := parseID(id, "supply id")
	if err != nil {
		return nil, err
	}

	supply, err := r.services.Supplies.GetByID(ctx, supplyID)
	if err != nil {
		return nil, err
	}

	return toGraphQLSupply(*supply), nil
}

// OutboundRequests is the resolver for the outboundRequests field.
func (r *queryResolver) OutboundRequests(ctx context.Context, warehouseID *string, status *string, limit *int, offset *int) ([]*model.OutboundRequest, error) {
	parsedWarehouseID, err := parseOptionalID(warehouseID, "warehouse id")
	if err != nil {
		return nil, err
	}
	var statusFilter *domain.OutboundRequestStatus
	if status != nil {
		value := domain.OutboundRequestStatus(*status)
		statusFilter = &value
	}

	requests, err := r.services.OutboundRequests.List(ctx, application.OutboundRequestFilter{
		WarehouseID: parsedWarehouseID,
		Status:      statusFilter,
		ListOptions: listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequests(requests), nil
}

// OutboundRequest is the resolver for the outboundRequest field.
func (r *queryResolver) OutboundRequest(ctx context.Context, id string) (*model.OutboundRequest, error) {
	requestID, err := parseID(id, "outbound request id")
	if err != nil {
		return nil, err
	}

	request, err := r.services.OutboundRequests.GetByID(ctx, requestID)
	if err != nil {
		return nil, err
	}

	return toGraphQLOutboundRequest(*request), nil
}

// Transfers is the resolver for the transfers field.
func (r *queryResolver) Transfers(ctx context.Context, warehouseID *string, sourceWarehouseID *string, targetWarehouseID *string, status *string, limit *int, offset *int) ([]*model.Transfer, error) {
	parsedWarehouseID, err := parseOptionalID(warehouseID, "warehouse id")
	if err != nil {
		return nil, err
	}
	parsedSourceWarehouseID, err := parseOptionalID(sourceWarehouseID, "source warehouse id")
	if err != nil {
		return nil, err
	}
	parsedTargetWarehouseID, err := parseOptionalID(targetWarehouseID, "target warehouse id")
	if err != nil {
		return nil, err
	}
	var statusFilter *domain.TransferStatus
	if status != nil {
		value := domain.TransferStatus(*status)
		statusFilter = &value
	}

	transfers, err := r.services.Transfers.List(ctx, application.TransferFilter{
		WarehouseID:       parsedWarehouseID,
		SourceWarehouseID: parsedSourceWarehouseID,
		TargetWarehouseID: parsedTargetWarehouseID,
		Status:            statusFilter,
		ListOptions:       listOptions(limit, offset),
	})
	if err != nil {
		return nil, err
	}

	return toGraphQLTransfers(transfers), nil
}

// Transfer is the resolver for the transfer field.
func (r *queryResolver) Transfer(ctx context.Context, id string) (*model.Transfer, error) {
	transferID, err := parseID(id, "transfer id")
	if err != nil {
		return nil, err
	}

	transfer, err := r.services.Transfers.GetByID(ctx, transferID)
	if err != nil {
		return nil, err
	}

	return toGraphQLTransfer(*transfer), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
