// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsActive    bool   `json:"isActive"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type CategoryInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type CreateOutboundRequestInput struct {
	WarehouseID     string `json:"warehouseID"`
	CreatedByUserID string `json:"createdByUserID"`
}

type CreateSupplyInput struct {
	WarehouseID     string `json:"warehouseID"`
	CreatedByUserID string `json:"createdByUserID"`
}

type CreateTransferInput struct {
	SourceWarehouseID string `json:"sourceWarehouseID"`
	TargetWarehouseID string `json:"targetWarehouseID"`
	CreatedByUserID   string `json:"createdByUserID"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

type Movement struct {
	Kind               string  `json:"kind"`
	OperationID        string  `json:"operationID"`
	OperationItemID    string  `json:"operationItemID"`
	ProductID          string  `json:"productID"`
	WarehouseID        string  `json:"warehouseID"`
	RelatedWarehouseID *string `json:"relatedWarehouseID,omitempty"`
	Quantity           int     `json:"quantity"`
	Status             string  `json:"status"`
	OccurredAt         string  `json:"occurredAt"`
}

type Mutation struct {
}

type OutboundRequest struct {
	ID                string                 `json:"id"`
	WarehouseID       string                 `json:"warehouseID"`
	Status            string                 `json:"status"`
	CreatedByUserID   string                 `json:"createdByUserID"`
	ApprovedByUserID  *string                `json:"approvedByUserID,omitempty"`
	ExecutedByUserID  *string                `json:"executedByUserID,omitempty"`
	CancelledByUserID *string                `json:"cancelledByUserID,omitempty"`
	Items             []*OutboundRequestItem `json:"items"`
	CreatedAt         string                 `json:"createdAt"`
	UpdatedAt         string                 `json:"updatedAt"`
	ApprovedAt        *string                `json:"approvedAt,omitempty"`
	ExecutedAt        *string                `json:"executedAt,omitempty"`
	CancelledAt       *string                `json:"cancelledAt,omitempty"`
}

type OutboundRequestItem struct {
	ID                string `json:"id"`
	OutboundRequestID string `json:"outboundRequestID"`
	ProductID         string `json:"productID"`
	Quantity          int    `json:"quantity"`
}

type OutboundRequestItemInput struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Sku               string `json:"sku"`
	CategoryID        string `json:"categoryID"`
	UnitOfMeasure     string `json:"unitOfMeasure"`
	MinStockThreshold int    `json:"minStockThreshold"`
	IsActive          bool   `json:"isActive"`
	CreatedAt         string `json:"createdAt"`
	UpdatedAt         string `json:"updatedAt"`
}

type ProductInput struct {
	Name              string `json:"name"`
	Sku               string `json:"sku"`
	CategoryID        string `json:"categoryID"`
	UnitOfMeasure     string `json:"unitOfMeasure"`
	MinStockThreshold int    `json:"minStockThreshold"`
	IsActive          *bool  `json:"isActive,omitempty"`
}

type Query struct {
}

type StockItem struct {
	ID          string `json:"id"`
	WarehouseID string `json:"warehouseID"`
	ProductID   string `json:"productID"`
	Quantity    int    `json:"quantity"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type StockStatus struct {
	StockItem *StockItem `json:"stockItem"`
	Product   *Product   `json:"product"`
	State     string     `json:"state"`
}

type Supply struct {
	ID                string        `json:"id"`
	WarehouseID       string        `json:"warehouseID"`
	Status            string        `json:"status"`
	CreatedByUserID   string        `json:"createdByUserID"`
	ConfirmedByUserID *string       `json:"confirmedByUserID,omitempty"`
	CancelledByUserID *string       `json:"cancelledByUserID,omitempty"`
	Items             []*SupplyItem `json:"items"`
	CreatedAt         string        `json:"createdAt"`
	UpdatedAt         string        `json:"updatedAt"`
	ConfirmedAt       *string       `json:"confirmedAt,omitempty"`
	CancelledAt       *string       `json:"cancelledAt,omitempty"`
}

type SupplyItem struct {
	ID             string `json:"id"`
	SupplyID       string `json:"supplyID"`
	ProductID      string `json:"productID"`
	Quantity       int    `json:"quantity"`
	UnitPriceCents int    `json:"unitPriceCents"`
}

type SupplyItemInput struct {
	ProductID      string `json:"productID"`
	Quantity       int    `json:"quantity"`
	UnitPriceCents int    `json:"unitPriceCents"`
}

type TotalStock struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type Transfer struct {
	ID                string          `json:"id"`
	SourceWarehouseID string          `json:"sourceWarehouseID"`
	TargetWarehouseID string          `json:"targetWarehouseID"`
	Status            string          `json:"status"`
	CreatedByUserID   string          `json:"createdByUserID"`
	ConfirmedByUserID *string         `json:"confirmedByUserID,omitempty"`
	CancelledByUserID *string         `json:"cancelledByUserID,omitempty"`
	Items             []*TransferItem `json:"items"`
	CreatedAt         string          `json:"createdAt"`
	UpdatedAt         string          `json:"updatedAt"`
	ConfirmedAt       *string         `json:"confirmedAt,omitempty"`
	CancelledAt       *string         `json:"cancelledAt,omitempty"`
}

type TransferItem struct {
	ID         string `json:"id"`
	TransferID string `json:"transferID"`
	ProductID  string `json:"productID"`
	Quantity   int    `json:"quantity"`
}

type TransferItemInput struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type UpdateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Role     string `json:"role"`
	IsActive bool   `json:"isActive"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	IsActive  bool   `json:"isActive"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Warehouse struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Location  string `json:"location"`
	IsActive  bool   `json:"isActive"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type WarehouseInput struct {
	Name     string  `json:"name"`
	Code     string  `json:"code"`
	Location *string `json:"location,omitempty"`
	IsActive *bool   `json:"isActive,omitempty"`
}
